version: '3.9'

services:

  app-thymeleaf-springboot:
    #image pull from docker hub
    image: lamineniang/hopital:0.0.1
    container_name: container-thymeleaf-springboot
    ports:
      - "8080:8080"
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      directoryDatas: /app/data/
    volumes:
      - datas:/app/data

volumes:
  datas: