name: build and deploy image
on: [push]

jobs:
  # Job 1: Build
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Create directory for Uploading artifacts
        run: mkdir staging && cp target/hopital-0.0.1.jar staging/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hopital-jar
          path: staging
          if-no-files-found: error
          retention-days: 5

      - name: Show uploaded artifacts
        run: ls staging/

      - run: echo "🍏 Build job completed with status ${{ job.status }}."

  # Job 2: Deploy
  deploy:
    name: Deploy job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Download the JAR artifact generated from the build job
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: hopital-jar

      - name: Show downloaded artifacts
        run: ls .

      # Build Docker image and push to Docker Hub
      - name: Build Docker image
        run: docker build --no-cache -t lamineniang99/hopital:0.0.1 .

      - name: Show Docker images
        run: docker image ls

      - name: print the credential in the stdin
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin



      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to DockerHub
        run: docker push lamineniang99/hopital:0.0.1

      - run: echo "🍏 Deploy job completed with status ${{ job.status }}."
